# This is a basic workflow to help you get started with Actions

name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bump version and push tag
      id: bump_version
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: minor

    - name: Build, tag, and push Docker image to Amazon ECR
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: false
        tags: |
         ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.bump_version.outputs.new_tag || github.head_ref }}-${{ github.sha }}
